# Generated by Django 4.2.1 on 2023-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enemy')),
                ('hit_points', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Player'),
        ),
    ]
