# Generated by Django 4.2.1 on 2023-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_enemy_user_attack_user_damage_user_defense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='weapon')),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name_plural': 'enemies'},
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='damage',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='damage',
            new_name='speed',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(default='enemy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='player'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='weapon',
            field=models.ManyToManyField(blank=True, related_name='enemy', to='adventure.weapon'),
        ),
        migrations.AddField(
            model_name='user',
            name='weapon',
            field=models.ManyToManyField(blank=True, related_name='user', to='adventure.weapon'),
        ),
    ]
