# Generated by Django 4.2.1 on 2023-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_weapon_alter_enemy_options_rename_damage_enemy_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
