# Generated by Django 4.2.1 on 2023-05-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_user_losses_user_wins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='losses',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wins',
            new_name='kills',
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weapon',
        ),
        migrations.AddField(
            model_name='enemy',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='adventure.weapon'),
        ),
        migrations.AddField(
            model_name='user',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='adventure.weapon'),
        ),
    ]
