# Generated by Django 4.2.1 on 2023-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='player'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_points',
            field=models.IntegerField(default=0),
        ),
    ]
