# Generated by Django 4.2.1 on 2023-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_user_name_user_skill_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(default='enemy', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='player', max_length=100),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='weapon', max_length=100),
        ),
    ]
